ALTER TABLE {$wpdb->prefix}wpjb_alert CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci; --
ALTER TABLE {$wpdb->prefix}wpjb_application CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci; --
ALTER TABLE {$wpdb->prefix}wpjb_company CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci; --
ALTER TABLE {$wpdb->prefix}wpjb_discount CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci; --
ALTER TABLE {$wpdb->prefix}wpjb_import CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci; --
ALTER TABLE {$wpdb->prefix}wpjb_job CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci; --
ALTER TABLE {$wpdb->prefix}wpjb_job_search CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci; --
ALTER TABLE {$wpdb->prefix}wpjb_mail CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci; --
ALTER TABLE {$wpdb->prefix}wpjb_membership CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci; --
ALTER TABLE {$wpdb->prefix}wpjb_meta CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci; --
ALTER TABLE {$wpdb->prefix}wpjb_meta_value CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci; --
ALTER TABLE {$wpdb->prefix}wpjb_payment CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci; --
ALTER TABLE {$wpdb->prefix}wpjb_pricing CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci; --
ALTER TABLE {$wpdb->prefix}wpjb_resume CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci; --
ALTER TABLE {$wpdb->prefix}wpjb_resume_detail CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci; --
ALTER TABLE {$wpdb->prefix}wpjb_resume_search CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci; --
ALTER TABLE {$wpdb->prefix}wpjb_shortlist CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci; --
ALTER TABLE {$wpdb->prefix}wpjb_tag CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci; --
ALTER TABLE {$wpdb->prefix}wpjb_tagged CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci; --
